### ISSUE TITLE
Consider to make (some of) our default Salt formulas oneshot instead of permanent

### ISSUE THREAD

**Issue by rootkovska** [QubesOS/qubes-issues#2173]
E.g. `sys-net-with-usb.sls` defines the default Net/USB VM in the following way:

```
  qvm.prefs:
    - name: {{ vmname }}
    - pcidevs: {{ salt['grains.get']('pci_net_devs', []) + salt['grains.get']('pci_usb_devs', []) }}
    - pci_strictreset: False
    - require:
      - sls: qvm.sys-net

```

This means the list of PCI devices is strictly defined. Now, imagine a user would like to add an additional PCI devices to be also handled by this VM (a typical example for most laptops would be an SD card reader, which often is exposed as a PCIe device). Nothing prevents the user from doing that. However, once this is done, the execution of `highstate` action would always result in an error, because Salt would detect the VM has a different property (i.e. a different list of PCI devs), and would attempt to correct this, but qvm-pci would, of course, fail, because the VM would be running.

Even more problematic, however, this would be if the VM was not running -- in that case the Salt stack would silently override the user's decision to have this particular additional device sandboxed.

I think most (all) states relating to the creation of VMs, especially by firstboot, should be oneshot. This is unlike some other states, such as e.g. for keeping the system up to date.
