### ISSUE TITLE
pkg.installed salt state fails with yum error message

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#2223]
#### Qubes OS version (e.g., `R3.1`):

R3.2-rc2
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

the issue is entirely in dom0

---
### Expected behavior:

`pkg.installed` salt state module function works as advertised.
### Actual behavior:

`pkg.installed` fails.
### Steps to reproduce the behavior:

``` yaml
packages-dom0:
  pkg.installed:
    - pkgs:
      - terminus-fonts
```

Note that `terminus-fonts` package is arbitrary, probably any package triggers this bug.
### General notes:

The error message contains `yum` help and the note suggesting some command line parameters are wrong.

---
