### ISSUE TITLE
Improve documentation on installing KDE in dom0

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2663]
These are the packages needed:

    packages:
    - plasma-workspace
    - plasma-systemsettings
    - plasma-breeze
    - kde-settings-plasma
    - plasma-desktop
    - kwin
    - kscreen

Note the missing package in #2662 .

Here is an Ansible playbook that deploys KDE and works around some issues of KDE not being present in the base image:

```
- hosts: dom0
  become: true
  vars:
    packages:
    - plasma-workspace
    - plasma-systemsettings
    - plasma-breeze
    - kde-settings-plasma
    - plasma-desktop
    - kwin
    - kscreen
  tasks:
  - name: install required software
    shell: qubes-dom0-update -y {{ " ".join(packages) }}
    register: dom0install
    changed_when: '{{ "Nothing to do" not in dom0install.stdout }}'
  - name: fix PAM settings for kscreensaver so the screen can be unlocked
    shell: |
      cd /etc/pam.d
      diff kscreensaver xscreensaver > /dev/null && {
        echo ALREADY
      } || {
        test -f kscreensaver.bak || cp -f kscreensaver kscreensaver.bak
        cat xscreensaver > kscreensaver
      }
    register: kscreensaverfix
    changed_when: '{{ "ALREADY" not in kscreensaverfix.stdout }}'
```
