### ISSUE TITLE
pvgrub boot: stuck at trying to make /dev/mapper/dmroot appear

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#2788]
Latest F25 and R3.2 software.

With this playbook (which details the steps) running against both `dom0` and a standalone AppVM called `testply`:

```yaml
- hosts: dom0
  become: yes
  tasks:
  - include_role:
      name: install-packages
    vars:
      packages:
      - grub2-xen

- hosts: testply
  become: yes
  tasks:
  - ini_file:
      path: /etc/yum.repos.d/qubes-r3.repo
      section: qubes-vm-r3.2-current
      option: exclude
      value: kernel, kernel-devel
  - shell: rpm -q kernel-devel | grep qubes && { rpm -e --nodeps kernel-devel ; exit $? ; } || true
  - package: name=qubes-kernel-vm-support,kernel-modules,kernel-devel,grub2-tools,dkms state=present
  - shell: rpm -q kernel-devel --queryformat="%{version}-%{release}.%{arch}"
    register: kver
    check_mode: no
    changed_when: no
  - package: name=kernel-{{ kver.stdout }} state=present
  - shell: /usr/sbin/qubes-prepare-vm-kernel {{ kver.stdout }}
  - lineinfile: state=present create=true dest=/etc/default/grub regexp="^GRUB_TIMEOUT=" line="GRUB_TIMEOUT=0"
  - shell: grub2-mkconfig -o /boot/grub2/grub.cfg

- hosts: dom0
  tasks:
  - shell: qvm-prefs testply -s kernel pvgrub2

- hosts: testply
  become: yes
  tasks:
  - include: tasks/reboot.yml
  - action: setup
```

After the reboot, `testply` hangs at the initrd stage, reaching target *Basic System* and going no further.  Eventually, boot gives up and says it got tired of waiting for `/dev/mapper/dmroot`.
