### ISSUE TITLE
Qubesctl incorrect return code

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#4464]
### Qubes OS version:

R4.0

### Affected component(s): 

Qubes Management stack

---

### Steps to reproduce the behavior:

Attempt to untar non-existent file:
```
nonexistent.tar.xz:
  module.run:
    - name: archive.tar
    - tarfile:nonexistent.tar.xz
    - options: -x -f
    - dest: /home/user
```

### Expected behavior:

Qubesctl returns Error

### Actual behavior:

Qubesctl returns OK.
log shows error: file not found

### General notes:

This isn't the only case where the return is misleading.
Similar issues have been referred to on the mailing lists, but I cant find anything in issues.
Currently I always review the logs, because I dont trust the output from qubesctl.
This seems a major impediment to use of qubesctl.

---

### Related issues:

#4177 also refers to the lack of error information. But in that case it seems that the lack of error is by design.
