### ISSUE TITLE
PVH doesn't work. PV does.

### ISSUE THREAD

**Issue by mfp20** [QubesOS/qubes-issues#5360]
(see below for HW/SW info)

I installed both 4.0.1 and 4.0.2-rc1 but the end result is always the same:
1) **sys-firewall creation fails at configuration** (after 1st reboot). Error message is about an internal error, "libxenlight failed to create" or alike.
2) **VMs fail to start unless I change PVH to PV**.
3) **appmenus fail to update, untill I update the template VMs**.

I've spotted similar issues, without clear solution ([example](https://github.com/QubesOS/qubes-issues/issues/3125)).

The same system, rebooted into another linux distro (kernel 5.2.17), runs properly a KVM/Qemu4 Win10 system with dedicated GPU passtrough. So **VT-d and VT-x are properly enabled in bios**.

As the pcie ethernet device is part of a wider IOMMU group, I tried to remove the ethernet device from the sys-net VM, but didn't change anything: sys-net in PVH mode doesn't start.

I tried to update both dom0 and the TemplateVMs but problem persist: no PVH (and HVM).

Feel free to ask for logs, install upgraded packages or applying patches.

---
```
layout: 'hcl'
type: 'desktop'
hvm: 'yes'
iommu: 'yes'
slat: 'yes'
tpm: 'unknown'
remap: 'yes'
brand: ASUSTeK COMPUTER INC.
model: SABERTOOTH 990FX R3.0
bios: 0212
cpu-short: AMD FX-9590
chipset-short: 990FX
gpu-short:
  RX550
  RX580
network: Intel Corporation I211 Gigabit Network Connection (rev 03)
memory: 32660
scsi: none
usb: 10
versions:
- works: partial
  qubes: 4.0.2-rc1
  xen: 4.8.5-7.fc25
  kernel: 4.19.71-1
  remark: sys-firewall creation fails. Starting VMs fails. Can be fixed
  changing the virtualization mode from PVH to PV.
  credit: mfp
  link: github mfp20
```
---
