### ISSUE TITLE
Boot using rEFInd ?

### ISSUE THREAD

**Issue by mfp20** [QubesOS/qubes-issues#5361]
Up to this moment I've been able to boot using a custom entry made with efibootmgr. I need to boot using rEFInd. Are there examples somewhere?

My current rEFInd entry (not booting):

```
menuentry "Qubes Dom0" {
        volume xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
        loader /EFI/qubes/xen-4.8.5-7.fc25.efi
        options "placeholder console=none dom0_mem=min:2048M dom0_mem=max:8192M"
}
```

---
HW/SW info:
```
layout: 'hcl'
type: 'desktop'
hvm: 'yes'
iommu: 'yes'
slat: 'yes'
tpm: 'unknown'
remap: 'yes'
brand: ASUSTeK COMPUTER INC.
model: SABERTOOTH 990FX R3.0
bios: 0212
cpu-short: AMD FX-9590
chipset-short: 990FX
gpu-short:
  RX550
  RX580
network: Intel Corporation I211 Gigabit Network Connection (rev 03)
memory: 32660
scsi: none
usb: 10
versions:
- works: partial
  qubes: 4.0.2-rc1
  xen: 4.8.5-7.fc25
  kernel: 4.19.71-1
  remark: sys-firewall creation fails. Starting VMs fails. Can be fixed
  changing the virtualization mode from PVH to PV.
  credit: mfp
  link: github mfp20
```
---
