### ISSUE TITLE
Make salt dom0 update output less noisy when logged

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#6165]
**The problem you're addressing (if any)**

When I do:

```
sudo qubesctl --show-output state.sls update.qubes-dom0 2>&1 | tee dom0.log
```

The log file looks like this:

```
ESC[0;32mlocal:ESC[0;0m
ESC[0;32m----------ESC[0;0m
    ESC[0;32m      ID: /etc/yum.repos.d/qubes-dom0.repoESC[0;0m
    ESC[0;32mFunction: file.replaceESC[0;0m
    ESC[0;32m  Result: TrueESC[0;0m
    ESC[0;32m Comment: No changes needed to be madeESC[0;0m
    ESC[0;32m Started: 05:08:53.886282ESC[0;0m
    ESC[0;32mDuration: 7.767 msESC[0;0m
ESC[0;32m     Changes:   ESC[0;0m
ESC[0;32m----------ESC[0;0m
    ESC[0;32m      ID: /etc/yum.repos.d/qubes-templates.repoESC[0;0m
    ESC[0;32mFunction: file.replaceESC[0;0m
    ESC[0;32m  Result: TrueESC[0;0m
    ESC[0;32m Comment: No changes needed to be madeESC[0;0m
    ESC[0;32m Started: 05:08:53.894159ESC[0;0m
    ESC[0;32mDuration: 1.301 msESC[0;0m
ESC[0;32m     Changes:   ESC[0;0m
ESC[0;32m----------ESC[0;0m
    ESC[0;32m      ID: updateESC[0;0m
    ESC[0;32mFunction: pkg.uptodateESC[0;0m
    ESC[0;32m  Result: TrueESC[0;0m
    ESC[0;32m Comment: System is already up-to-dateESC[0;0m
    ESC[0;32m Started: 05:08:54.620104ESC[0;0m
    ESC[0;32mDuration: 387424.021 msESC[0;0m
ESC[0;32m     Changes:   ESC[0;0m
ESC[0;36m
Summary for local
------------ESC[0;0m
ESC[0;32mSucceeded: 3ESC[0;0m
ESC[0;36mFailed:    0ESC[0;0m
ESC[0;36m------------
Total states run:     3ESC[0;0m
ESC[0;36mTotal run time: 387.433 sESC[0;0m
```

This is what I mean by "noisy." For comparison, when I do:

```
sudo qubesctl --show-output --skip-dom0 --templates state.sls update.qubes-vm 2>&1 | tee template.log
```

The log file looks nice and clean, like this:

```
[...]
  ----------
            ID: dnf list updates --refresh >/dev/null
      Function: cmd.run
        Result: True
       Comment: Command "dnf list updates --refresh >/dev/null" run
       Started: 05:16:05.468843
      Duration: 63054.633 ms
       Changes:   
                ----------
                pid:
                    876
                retcode:
                    0
                stderr:
                stdout:
  ----------
            ID: update
      Function: pkg.uptodate
        Result: True
       Comment: Upgrade ran successfully
       Started: 05:17:11.079770
      Duration: 61790.03 ms
       Changes:   
[...]
  ----------
            ID: notify-updates
      Function: cmd.run
          Name: /usr/lib/qubes/upgrades-status-notify
        Result: True
       Comment: Command "/usr/lib/qubes/upgrades-status-notify" run
       Started: 05:18:12.871181
      Duration: 4775.399 ms
       Changes:   
                ----------
                pid:
                    1305
                retcode:
                    0
                stderr:
                stdout:
[...]
```

**Describe the solution you'd like**

Make the dom0 log output just as clean as templates.

**Where is the value to a user, and who might that user be?**

Value: more readable logs.
Who: Anyone who logs this output, like me. :slightly_smiling_face: 

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

N/A

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found.
