### ISSUE TITLE
qubes-mgmt-salt-dom0-update-4.1.7 breaks fc32 updates

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#6955]
### Qubes OS release

4.1beta

### Brief summary

After installing the version fixing #6522 as described in [this comment](https://github.com/QubesOS/qubes-issues/issues/6522#issuecomment-939099120) and following ones, a fc32 VM does not even updates the  list of available packages because of dependency chain rooted at unsatisfiable `dnf>= 4.7.0`:

```
  ----------
            ID: dnf-and-rpm
      Function: pkg.installed
        Result: False
       Comment: Error occurred installing package(s). Additional info follows:
                
                errors:
                    - No version matching 'dnf>= 4.7.0' could be found (available: 4.6.0-1.fc32, 4.2.19-1.fc32)
       Started: 18:30:09.708748
      Duration: 17081.663 ms
       Changes:   
  ----------
            ID: /usr/lib/rpm/macros.d/macros.qubes
      Function: file.absent
        Result: False
       Comment: One or more requisite failed: update.qubes-vm.dnf-and-rpm
       Started: 18:30:26.796857
      Duration: 0.006 ms
       Changes:   
  ----------
...
  ----------
            ID: update
      Function: pkg.uptodate
        Result: False
       Comment: One or more requisite failed: update.qubes-vm./usr/lib/rpm/macros.d/macros.qubes
       Started: 18:30:31.301591
      Duration: 0.003 ms
       Changes:   
  ----------
```
