### ISSUE TITLE
[salt] Wrong rendering of pillar data

### ISSUE THREAD

**Issue by p1llule** [QubesOS/qubes-issues#6997]
### Qubes OS release
4.0

### Brief summary

Making a pillar with jinja does not reflect the grains of the targeted virtual machine.

### Steps to reproduce

I have this in /srv/user_pillar/custom.sls :

```` sls
dependencies:
  - gcc:
{% if grains['os_family'] == 'RedHat' %}
    - libmpc-devel
    - isl-devel
    - gmp-devel
    - mpfr-devel
    - automake
    - 'gcc-c++'
    - kernel-devel
{% elif grains['os'] == 'Debian' %}
    - gcc
    - g++
    - libmpc-dev
    - libisl-dev
    - libgmp3-dev
    - libmpfr-dev
    - build-essential
{% endif %}
    - binutils
    - make
    - gzip
    - tar
    - m4
    - flexo
    - bison
    - autogen
    - dejagnu
````

I checked `grains.get os` and `grains.get os_family`, they are right.
I want to uses it with an install.sls for a debian vm :

```` sls
installed:
  pkg.installed:
    - install_recommends: False
    - pkgs:
      - qubes-core-agent-networking
      - ripgrep
      - git
      - fd-find
      - shellcheck
{% for dep in salt['pillar.get']('dependencies:gcc') %}
      - {{ dep }}
{% endfor %}
````

However triggering that state will partially fail because the wrong dependencies are picked.

Using `sudo qubesctl --show-output --skip-dom0 --target=$DEBIAN_VM state.show_sls pathto.install.sls saltenv=user` makes it clearly apparent : 

````
    installed:
          ----------
          __env__:
              user
          __sls__:
              pathto.install
          pkg:
              |_
                ----------
                install_recommends:
                    False
              |_
                ----------
                pkgs:
                    - qubes-core-agent-networking
                    - ripgrep
                    - git
                    - fd-find
                    - shellcheck
                    - libmpc-devel
                    - isl-devel
                    - gmp-devel
                    - mpfr-devel
                    - automake
                    - gcc-c++
                    - kernel-devel
                    - binutils
                    - make
                    - gzip
                    - tar
                    - m4
                    - flexo
                    - bison
                    - autogen
                    - dejagnu
              - installed
              |_
                ----------
                order:
                    10015
````

### Expected behavior

Pillar should be rendered correctly for the target VM.

### Actual behavior

Nope.

### What I tried

I tried to set the default-mgmt-dvm template to a debian VM (and template dispvm too).
I dunno If then I need to restart salt somehow for that change to takes effect.
I precise I have that issue only with pillar. Jinja is rendered correctly if I use it in state files.

### Doc consulted

[saltstack, pillar page](https://docs.saltproject.io/en/latest/topics/tutorials/pillar.html)

**Comment by lkubb** [comment]
Afaik this might be due to [pillar data being compiled on dom0](https://github.com/QubesOS/qubes-mgmt-salt/blob/18f819faa164fa2abe2636e630e12f72dcf52b5d/qubessalt/__init__.py#L116-L126) and statically being passed by design, thus it always renders the Fedora case. Using grains to target pillars (except `grains['id']`) is [discouraged anyways](https://docs.saltproject.io/en/latest/faq.html#faq-grain-security). From experience, using `grains['id']` inside pillar files does work, but currently has some caching issues with salt-ssh and qubes specifically.

In your case the data is not sensitive, why don't you do this inside your salt state? That should work as intended. A little more elegant would be to use [grains.filter_by](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.filter_by).

e.g. as separate `map.jinja` or inside your .sls:
```jinja
{%- set dependencies = salt['grains.filter_by']({
  'RedHat': {
    'gcc': [
      'libmpc-devel',
      'isl-devel',
      'gmp-devel',
      'mpfr-devel',
      'automake',
      'gcc-c++,'
      'kernel-devel',
  ]},
  'Debian': {
    'gcc': [
      'gcc',
      'g++',
      'libmpc-dev',
      'libisl-dev',
      'libgmp3-dev',
      'libmpfr-dev',
      'build-essential'
  ]}} -%}
```
Then your state could look like this:
```salt
{%- from 'map.jinja' import dependencies -%} # if you choose the map.jinja route

installed:
  pkg.installed:
    - install_recommends: False
    - pkgs:
      - qubes-core-agent-networking
      - ripgrep
      - git
      - fd-find
      - shellcheck
{%- for dep in dependencies.get('gcc', []) %}
      - {{ dep }}
{%- endfor %}
```

**Comment by p1llule** [comment]
Yes, indeed I worked around that by not using pillars. Thanks for the example of map.jinja :)

**Comment by p1llule** [comment]
I found worse. 

let's say I have a pillar for a mail account.

```` yaml
account:
   user: p1llule
   password: das_pils
   address: p1llule@wont.reply
````

Then I want to acceed to that pillar in a state file :

```` yaml
{% set account = salt.pillar.get('account') %}

echo {{ account }}:
  cmd.run
````

I got that trace that complains about default value because it can't get the pillar data.
````
      - Rendering SLS 'user:test' failed: Jinja error: get() missing 1 required positional argument: 'default'
        Traceback (most recent call last):
          File "/usr/lib/python3.9/site-packages/salt/utils/templates.py", line 500, in render_jinja_tmpl
            output = template.render(**decoded_context)
          File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 1090, in render
            self.environment.handle_exception()
          File "/usr/lib/python3.9/site-packages/jinja2/environment.py", line 832, in handle_exception
            reraise(*rewrite_traceback_stack(source=source))
          File "/usr/lib/python3.9/site-packages/jinja2/_compat.py", line 28, in reraise
            raise value.with_traceback(tb)
          File "<template>", line 1, in top-level template code
          File "/usr/lib/python3.9/site-packages/jinja2/sandbox.py", line 462, in call
            return __context.call(__obj, *args, **kwargs)
        TypeError: get() missing 1 required positional argument: 'default'
        
        ; line 1
        
        ---
        {% set mail = salt.pillar.get('account') %}    <======================
        
        echo {{ mail }}:
          cmd.run
        
        Traceback (most recent call last):
        [...]
        ---
````

Importing a jinja file is of no help here, the same context will lead to the same failure.

I notice that if instead I do the templating in another file with something like:
```` yaml
/home/user/mail.conf:
  file.managed:
     - user: user
     - mode: user
     - template: jinja
     - source: salt://somewhere
````

The pillar data is acquired !

Unfortunately that is not a solution because it is important to be able to do conditionals in the state file.

**Comment by marmarek** [comment]
> TypeError: get() missing 1 required positional argument: 'default'

Have you tried adding that parameter to your `salt.pillar.get` call?

**Comment by p1llule** [comment]
Yes but that is irrelevant : Salt only throw that error because in the first place it was unable to get the pillar data.

**Comment by unman** [comment]
"I found worse." makes it sound as if you dont think you can use pillar
data at all.
This is obviously wrong - I say "obviously" because Qubes uses pillar
data.
So do I in configuring templates and qubes.


Here's a basic example:  

```` yaml
mail_account:
  user: p1llule
  password: das_pils
  address: ***@***.***
````

`qubesctl --skip-dom0 --show-output --targets=TARGET_QUBE pillar.items`
will confirm that the pillar is usable.

Then you can access the pillar data:

```` yaml
Add_mail_user:
  user.present:
    - name: {{ salt['pillar.get']('mail_account:username') }}
````

And call that state file as normal.


If you want the whole dictionary:

```` yaml
{%- set account_to_create = pillar.get('mail_account') %}

Add_mail_user:
  user.present:
    - name: {{ account_to_create["username"] }}
````

Does that help?
Checking that the pillar is available with `pillar.items` is useful in
debugging.


I'll take a look at your original issue later.
