### ISSUE TITLE
salt: storage pool management

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#8102]
### The problem you're addressing (if any)

There's no way to create qubes storage pool (`qvm-pool --add`)

### The solution you'd like

```yaml
pool-name:
  qvm-pool.present:
    - driver: lvm_thin
    - options:
        - volume_group: pool-vg
        - thin_pool: pool-thin
        - revisions_to_keep: 17

other-pool-name:
  qvm-pool.absent: []
```

and respective module with functions for `qvm-pool --list` and `qvm-pool --info`
