### ISSUE TITLE
Configure `qubes-network-uplink.service` to start automatically upon package installation

### ISSUE THREAD

**Issue by czepiec** [QubesOS/qubes-issues#8450]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

Qubes OS 4.1

### Brief summary

In the case of a Fedora minimal VM (and potentially other minimal templates), installation of `qubes-core-agent-networking` does not trigger the automatic startup of the `qubes-network-uplink.service`. As a result, there is no network connection in the VM until the user manually initiates the service by executing `systemctl start qubes-network-uplink` or by restarting the VM.

Unless there are security implications that necessitate the current behavior, I propose that the `qubes-network-uplink.service` be configured to start automatically upon package installation. This aligns with common practice in the Linux community, where services installed without requiring system (or VM) restarts are usually started automatically. This change would be particularly beneficial for users who are setting up new minimal VMs using Salt or command-line interfaces and need to install packages and software from the internet.

Moreover, it's worth considering that this suggestion might extend to other services as well, such as `qubes-network.service`, `qubes-firewall.service`, and potentially others.

### Steps to reproduce

- Clone or install clean fedora-38-minimal template
- Set net qube (e.g. to sys-firewall) for this template
- Start terminal
- Install `qubes-core-agent-networking` with `dnf install -y qubes-core-agent-networking`

### Expected behavior

There should be connectivity, e.g. `curl https://www.qubes-os.org` will work.

### Actual behavior

Lack of connectivity, e.g. `curl https://www.qubes-os.org` fails.

### Alternative steps to reproduce with Salt

User want to install Zoom (randomly selected software for this example) to fedora-38-minimal template.

- Clone or install clean fedora-38-minimal template
- Set net qube (e.g. to sys-firewall) for this template
- Run Salt file for this template:

```yaml
packages:
  pkg.latest:
  - pkgs:
    - qubes-core-agent-networking

zoom:
  file.managed:
  - name: /root/zoom.rpm
  - source: https://cdn.zoom.us/prod/5.15.10.6882/zoom_x86_64.rpm
  - skip_verify: true
  pkg.installed:
  - name: zoom
  - sources:
    - zoom: /root/zoom.rpm
```

Salt state fails because can't download rpm file from internet.
