### ISSUE TITLE
4.2-RC3: Qubes Application Menu isn't updated when using salt to modify menu-items

### ISSUE THREAD

**Issue by rapenne-s** [QubesOS/qubes-issues#8494]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2-RC3

### Brief summary

If you update a qube menu-items settings using salt, in the qube settings in the Applications tab, you can see the new list, but this doesn't show up in the new XFCE Qubes OS menu. Making a change in that list from the GUI correctly update the new menu though.

### Steps to reproduce

Make a salt state updating the menu items of a qube

```
create-qubes-xmpp:
  qvm.vm:
    - name: XMPP
    - present:
      - template: fedora-38
      - label: yellow
    - prefs:
      - label: yellow
    - features:
      - set:
        - menu-items: org.gnome.Terminal.desktop org.gnome.Nautilus.desktop im.dino.Dino.desktop
```

Use `qubesctl state.apply` to apply changes, it will report a success.

### Expected behavior

The menu items appear in the Qubes Application menu, and in the qube settings.

### Actual behavior

The menu items only appear in the qubes settings, not in the Qubes Application menu.
