### ISSUE TITLE
Setting no-strict-reset option via salt on already attached devices doesn't work

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8514]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 (R4.1 likely too)

### Steps to reproduce

Have this state:
```
sys-net-no-strict-reset:
  qvm.prefs:
  - name: sys-net
  - pci_strictreset: False
  - pcidevs: {{ salt['grains.get']('pci_net_devs', [])|yaml }}
```
Try to apply on already configured sys-net

### Expected behavior

`no-strict-reset` option gets enabled

### Actual behavior

Salt report no change ("[SKIP]") and indeed option is not set.
If devices were not attached to sys-net, setting the option does work.
