### ISSUE TITLE
split-gpg2 should source a configuration directory

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8792]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Configuration directory is very good for drop-in configurations.
Currently, if I want to deliver a configuration policy, it will overwrite user configuration in `~/.config/qubes-split-gpg2/qubes-split-gpg2.conf`.

### The solution you'd like

Include a configuration directory such as `~/.config/qubes/split-gpg2/conf.d/*.conf`.
This way, I can separate configuration from different clients:

`qubes-split-gpg2.conf`:
```toml
[DEFAULT]
autoaccept = 86400
```

`conf.d/work.conf`:
```toml
[client:work-code]
autoaccept = 86400
```

`conf.d/builder.conf`:
```toml
[client:qubes-builder]
autoaccept = 86400

[client:mirage-builder]
autoaccept = 86400
```

If configuration directories are sourced, I can add and remove configuration without messing with the user settings or using a toml parser when deploying with SaltStack.

### The value to a user, and who that user might be

User's can use a single split-gpg2 server and having configurations deployed in an idempotent manner.
Packagers can provide split-gpg2 configurations without overwriting user configuration when they deploy qubes for users such as `qubes-builder` or `qubes-secpack` qube with the necessary keys the split-gpg2 server to verify the repository.
