### ISSUE TITLE
Builder fails to get and verify sources because of missing tag

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8831]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2, qubes-builderv2.

### Brief summary

 Builder fail with unexpected missing tag.

### Steps to reproduce

HEAD is [cc433cb](https://github.com/QubesOS/qubes-builderv2/commit/cc433cb32f570ccb9ac8d7eeb0daa70ee3460643).

Command:
```sh
cp example-configs/qubes-os-r4.2-dom0.yml to builder.yml
# modify the config
./qb package fetch
```

Output:
```
[executor:qubes:disp2678] copy-in (cmd): /usr/bin/qvm-run-vm disp2678 bash -c 'rm -rf /builder/incoming/fetch /builder/plugins/fetch'
[executor:qubes:disp2678] copy-in (cmd): /usr/lib/qubes/qrexec-client-vm disp2678 qubesbuilder.FileCopyIn /usr/lib/qubes/qfile-agent /home/user/src/qubes-builderv2/qubesbuilder/plugins/fetch
[executor:qubes:disp2678] copy-in (cmd): /usr/bin/qvm-run-vm disp2678 bash -c 'mkdir -p /builder/plugins && mv /builder/incoming/fetch /builder/plugins'
[executor:qubes:disp2678] Executing '/usr/bin/qvm-run-vm disp2678 env VERBOSE='1' DEBUG='1' BACKEND_VMM='xen' bash -c 'cd /builder && /builder/plugins/fetch/scripts/get-and-verify-source.py https://github.com/QubesOS/qubes-builder-rpm.git /builder/builder-rpm /builder/keyring /builder/plugins/fetch/keys --git-branch main --minimum-distinct-maintainers 1 --fetch-versions-only''.
[executor:qubes:disp2678] output: No version tag
```

### Expected behavior

No missing tag on https://github.com/QubesOS/qubes-builder-rpm.git.

### Actual behavior

Missing tag.

**Comment by fepitre** [comment]
Can you please share you `builder.yml`, the problem identified is unrelated to missing tag, it's related to version tag. There will be never version tag in builder plugins for now. I'm suspecting that `packages: false` is missing in `builder-rpm` into your conf?

**Comment by ben-grande** [comment]
I copied from [example-configs/qubes-os-r4.2-dom0.yml](https://github.com/QubesOS/qubes-builderv2/blob/main/example-configs/qubes-os-r4.2-dom0.yml) and only changed `executor:options:dispvm` to my needs:
```yaml
include:
  - example-configs/qubes-os-r4.2.yml
  - example-configs/qubes-os-r4.2-maintainers.yml
#  - example-configs/github.yml
#  - example-configs/github-maintainers.yml

git:
  baseurl: https://github.com
  prefix: QubesOS/qubes-
  branch: main

backend-vmm: xen
debug: true
verbose: true
qubes-release: r4.2
timeout: 3600

skip-git-fetch: false
fetch-versions-only: true

distributions:
  - host-fc37

+components:
  - release-configs:
      packages: false

executor:
  type: qubes
  options:
    dispvm: "dvm-qubes-builder"

stages:
  - fetch
  - pre:
      executor:
        type: local
  - prep
  - build
  - post:
      executor:
        type: local
  - verify
  - sign:
      executor:
        type: local
  - publish:
      executor:
        type: local
  - upload:
      executor:
        type: local

gpg-client: qubes-gpg-client-wrapper

sign-key:
  rpm: 77EEEF6D0386962AEA8CF84A9B8273F80AC219E6

repository-publish:
  components: current-testing

#repository-upload-remote-host:
#  rpm: user@yum.qubes-os.org:/some/path
#  deb: user@deb.qubes-os.org:/another/path
```

And from what I can see,  `packages: false`:
```yaml
+components:
  - release-configs:
      packages: false
```
