### ISSUE TITLE


I think distributing a salt file to configure a Qubes OS developing environment is better than maintaining and distributing a full template.

### ISSUE THREAD

**Issue by tlaurion** [QubesOS/qubes-issues#8844]
I think distributing a salt file to configure a Qubes OS developing environment is better than maintaining and distributing a full template. 

In fact I have made something for myself:

fed-min-qubes-dev.sls:
```
{% set fedoraver = salt['pillar.get']('fedoraver', 'fedora-38') %}

include:
  - prep

{% if grains['id'] == 'dom0' %}

create-{{ fedoraver }}-builder:
  qvm.clone:
    - name: {{ fedoraver }}-builder
    - source: {{ fedoraver }}-minimal
    - require:
      - qvm: ensure-{{ fedoraver }}-minimal-installed

create-qubes-builder-dvm:
  qvm.vm:
    - name: qubes-builder-dvm
    - present:
      - template: {{ fedoraver }}-builder
      - label: red
    - prefs:
      - virt_mode: pvh
      - label: red
      - template-for-dispvms: true
      - memory: 800
      - maxmem: 8000
      - vcpus: 6
    - require:
      - qvm: create-{{ fedoraver }}-builder

create-qubes-work:
  qvm.vm:
    - name: qubes-work
    - present:
      - template: {{ fedoraver }}-builder
      - label: red
    - prefs:
      - virt_mode: pvh
      - label: red
      - memory: 400
      - maxmem: 1000
      - default-dispvm: qubes-builder-dvm
    - require:  
      - qvm: create-qubes-builder-dvm

resize-builder-volume:
  cmd.run:
    - name: qvm-volume resize qubes-builder-dvm:private 32212254720 ;qvm-volume resize qubes-work:private 32212254720

builder-policy:
  file.managed:
    - name: /etc/qubes/policy.d/60-qubesbuilder.policy
    - contents: |
        admin.vm.CreateDisposable * qubes-work qubes-builder-dvm allow target=dom0
        admin.vm.Start * qubes-work @tag:disp-created-by-qubes-work allow target=dom0
        admin.vm.Kill * qubes-work @tag:disp-created-by-qubes-work allow target=dom0
        qubesbuilder.FileCopyIn * qubes-work @tag:disp-created-by-qubes-work allow
        qubesbuilder.FileCopyOut * qubes-work @tag:disp-created-by-qubes-work allow
        qubes.WaitForSession * qubes-work @tag:disp-created-by-qubes-work allow
        qubes.VMShell * qubes-work @tag:disp-created-by-qubes-work allow


{% elif grains['id'] == [fedoraver, '-builder']|join %}

update:
  cmd.run:
    - name: dnf install -y qubes-core-agent-networking qubes-core-agent-passwordless-root qubes-core-agent-thunar xfce4-terminal unzip wqy-microhei-fonts python3-packaging createrepo_c devscripts gpg python3-pyyaml rpm reprepro python3-pathspec mktorrent rpm-sign tree mock openssl python3-jinja2-cli m4 asciidoc rsync qubes-gpg-split dnf-plugins-core debootstrap dpkg-dev git mock pbuilder which perl-Digest-MD5 perl-Digest-SHA  python3-sh rpm-build rpmdevtools wget python3-debian python3-lxml systemd-udev python3-click qubes-gpg-split

{% elif grains['id'] == 'qubes-builder-dvm' %}

copyinout:
  cmd.run:
    - name: mkdir /usr/local/etc/qubes-rpc ; cd /usr/local/etc/qubes-rpc ; curl -o qubesbuilder.FileCopyIn -L https://raw.githubusercontent.com/QubesOS/qubes-builderv2/main/rpc/qubesbuilder.FileCopyIn ; curl -o qubesbuilder.FileCopyOut -L https://raw.githubusercontent.com/QubesOS/qubes-builderv2/main/rpc/qubesbuilder.FileCopyOut ; chmod a+x qubesbuilder.FileCopyOut ; chmod a+x qubesbuilder.FileCopyIn
       
builderdirectory:
  cmd.run:
    - name: mkdir -p /rw/bind-dirs/builder /rw/config/qubes-bind-dirs.d ; echo "binds+=('/builder')" > /rw/config/qubes-bind-dirs.d/builder.conf ;

appendrc:
  file.append:
    - name: /rw/config/rc.local
    - text: mount /builder -o dev,suid,remount

{% elif grains['id'] == 'qubes-work' %}

git-fetch:
  cmd.run:
    - name: cd /home/user ; git clone https://github.com/QubesOS/qubes-infrastructure-mirrors ; git clone /https://github.com/QubesOS/qubes-builderv2
    - runas: user
install-infrastructure:
  cmd.run:
    - name: cd /home/user/qubes-infrastructure-mirrors ; python3 setup.py build ; python3 setup.py install

{% endif %}
```

fed-min-qubes-dev.top:

```
{% set fedoraver = salt['pillar.get']('fedoraver', 'fedora-38') %}

user:
  dom0 or {{ fedoraver }}-builder or qubes-builder-dvm or qubes-work:
    - fed-min-qubes-dev
```

So this basically creates a template `fedora-38-builder` and configures it to be able to work as both the actual qubes executor and where qubes-builderv2 locates. And it creates `qubes-builder-dvm` which is the executor, and `qubes-work` which is where you work with the source code and issue commands to build the packages.

Update: Fixed the top file.

_Originally posted by @Augsch123 in https://github.com/QubesOS/qubes-issues/issues/8774#issuecomment-1867854489_
