### ISSUE TITLE
DNS leakage when only one DNS server is set in a NetVM

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#9011]
_Seen in 4.2._

One of my machines has a NetVM with a physical network interface, manually set to have only *one* DNS server (local).  In this scenario, the Qubes `dnat-dns` chain contains the following:

```
	chain dnat-dns {
		type nat hook prerouting priority dstnat; policy accept;
		ip daddr 10.139.1.1 udp dport 53 dnat to 10.250.7.2
		ip daddr 10.139.1.1 tcp dport 53 dnat to 10.250.7.2
	}
```

That's sensible.  Only one DNS server is mapped.

However, since the configuration of the qubes attached to this NetVM in fact contains internal Qubes IPs 10.139.1.1 _and 10.139.1.2_, sometimes (when the local DNS server fails to respond on time) the qubes issue a DNS request to 10.139.1.2, which is in fact routed out of the VM because nothing intercepts it (the `dnat-dns` chain doesn't have an entry for it.

(I caught this by observing very funny incomplete NAT entries in my border router, all mentioning internal Qubes IPs.)

Ideally, the `dnat-dns` chain adds rules for both IPs, and if it needs to repeat the same single DNS server IP address in both pairs of rules, then it should do so.

Thanks in advance for fixing this security issue.

In the meantime, to mitigate this, I've configured my custom firewalling to drop such traffic at the border router:

```
border-router:
  input_rules: *global_input
  forward_rules: *global_forward
  custom_chains:
    ip:
      custom-prerouting-dstnat:
        preamble: type nat hook prerouting priority dstnat -1; policy accept;
        rules:
          nodnsleak:
          - from: intranet
            to: 10.136.0.0/14
            action: drop
            log_prefix: "Dropping internal Qubes traffic: "
```
