### ISSUE TITLE
Inconsistent key name in salt states `qvm.prefs` and `qvm.present`

### ISSUE THREAD

**Issue by RandyTheOtter** [QubesOS/qubes-issues#9633]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.3

### Brief summary

`qvm.prefs` refers to memory as `memory`, whereas `qvm.present` refers to memory as `mem`.

### Steps to reproduce

Use aforementioned salt modules.

### Expected behavior

Both modules use identical key names for the same qube preferences. For example:

```yaml
whocares:
  qvm.prefs:
    - memory: 42069

wow:
  qvm.present:
    - memory: 1337
```

### Actual behavior

```yaml
whocares:
  qvm.prefs:
    - memory: 42069

wow:
  qvm.present:
    - mem: 1337
```
