### ISSUE TITLE
Document extrepo for installing software not in Debian repositories

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#9758]
### The problem you're addressing (if any)

Installing third-party programs (not in distro repos) like Signal and Element can be difficult.  Official installation instructions don’t work in templates because they require Internet access.

### The solution you'd like

Debian provides the extrepo mechanism for installing software not in Debian.  Together with extrepo-offline-data, it can be used to safely and securely install Element Desktop, Signal Desktop, and lots of other software.

Qubes OS should provide it by default with a reasonable configuration:

- `extrepo` and `extrepo-offline-data` packages installed.
- No external repos enabled.
- `extrepo` pointed at `file:///usr/share/extrepo/offline-data` by default:
  ```yaml
  ---
  url: file:///usr/share/extrepo/offline-data
  dist: debian
  version: bookworm
  # To enable repositories that host software with non-DFSG-free licenses,
  # uncomment "contrib" and/or "non-free" in the list below.
  enabled_policies:
  - main
  # - contrib
  # - non-free
  ```

Furthermore, its use should be documented, if only by linking to the Debian documentation.

### The value to a user and who that user might be

Users will safely be able to install third-party software.
