### ISSUE TITLE
Qubes-Ansible - undefine does not remove qube

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#9925]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
Running `undefine` state has no effect.

### Steps to reproduce
1. Create qube
2. Confirm qube is in inventory
3. Execute playbook:
```yaml
---
- hosts: local
  connection: local
  tasks:
      - name: Undefine a qube
        qubesos:
          guest: testqube
          state: undefine
```

### Expected behavior
In accordance with warning:
**Warning:** The `undefine` state will remove the qube and all associated data. Use with caution.

The qube will be removed.

### Actual behavior
No effect. The qube remains.

### Additional information
The same playbook using state `destroyed` *does* serve to kill the qube.

**Comment by TheVamp** [comment]
The `undefine` is not implemented. To remove a qube `absent` should be used.

The documentation from the source code:

```
  state:
    description:
      - Desired state of the VM.
      - When set to C(present), ensures the VM is defined.
      - When set to C(running), ensures the VM is started.
      - When set to C(shutdown), ensures the VM is stopped.
      - When set to C(destroyed), forces the VM to shut down.
      - When set to C(restarted), shuts the VM down then starts it again.
      - When set to C(pause), pauses a running VM.
      - When set to C(absent), removes the VM definition.
    choices: [ present, running, shutdown, destroyed, restarted, pause, absent ]
```

For the current version in the testing branch the behavior is correct. The playbook failed with the error message 

"value of state must be one of: destroyed, pause, running, shutdown, restarted, absent, present, got: undefine"

Used version:
- Dom0: qubes-ansible-dom0 1.2.1-1
- Disp-mgmt-dvm: qubes-ansible-vm 1.2.1-1

IMO the issue could be closed. The feature "to remove a qube" is implemented.
