### ISSUE TITLE
Qubes-Ansible - Cloning TemplatVM or creating StandaloneVM qubes fails

### ISSUE THREAD

**Issue by bcduggan** [QubesOS/qubes-issues#9932]
### Qubes OS release

Qubes OS 4.2

### Brief summary

Cloning a TemplateVM or creating a StandaloneVM from a TemplateVM fails.

### Steps to reproduce

1. Create and run a playbook with `state: present` where `vmtype: TemplateVM` or `vmtype: StandaloneVM`:

```yaml
---
- name: Clone qube
  hosts: local
  connection: qubes
  tasks:
    - name: Create fedora-41-xfce-clone
      qubesos:
        guest: fedora-41-xfce-clone
        state: present
        vmtype: TemplateVM
        template: fedora-41-xfce
```

### Expected behavior

After execution, a new qube should be present of the class in `vmtype`. If `vmtype` is `TemplateVM`, the label should be the same as the template. If `vmtype` is `StandaloneVM` and the class of the template is `TemplateVM`, the label should be the value of `label` in the task.

### Actual behavior

```console
mgmtvm$ ansible-playbook -vvv clone.yml
ansible-playbook [core 2.16.14]
  config file = /home/user/repos/qubes-ansible-site/ansible.cfg
  configured module search path = ['/home/user/repos/qubes-ansible-site/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.13/site-packages/ansible
  ansible collection location = /home/user/repos/qubes-ansible-site
  executable location = /usr/bin/ansible-playbook
  python version = 3.13.3 (main, Apr  9 2025, 00:00:00) [GCC 14.2.1 20250110 (Red Hat 14.2.1-7)] (/usr/bin/python3)
  jinja version = 3.1.6
  libyaml = True
Using /home/user/repos/qubes-ansible-site/ansible.cfg as config file
host_list declined parsing /home/user/repos/qubes-ansible-site/inventory.yml as it did not pass its verify_file() method
script declined parsing /home/user/repos/qubes-ansible-site/inventory.yml as it did not pass its verify_file() method
Parsed /home/user/repos/qubes-ansible-site/inventory.yml inventory source with yaml plugin
Skipping callback 'default', as we already have a stdout callback.
Skipping callback 'minimal', as we already have a stdout callback.
Skipping callback 'oneline', as we already have a stdout callback.

PLAYBOOK: test.yml *************************************************************
1 plays in test.yml

PLAY [Clone qube] **************************************************************

TASK [Gathering Facts] *********************************************************
task path: /home/user/repos/qubes-ansible-site/test.yml:2
<mgmtvm> ESTABLISH LOCAL CONNECTION FOR USER: user
<mgmtvm> EXEC /bin/sh -c 'echo ~user && sleep 0'
<mgmtvm> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1745956217.800708-12470-17428818468008 `" && echo ansible-tmp-1745956217.800708-12470-17428818468008="` echo /home/user/.ansible/tmp/ansible-tmp-1745956217.800708-12470-17428818468008 `" ) && sleep 0'
<mgmtvm> Attempting python interpreter discovery
<mgmtvm> EXEC /bin/sh -c 'echo PLATFORM; uname; echo FOUND; command -v '"'"'python3.12'"'"'; command -v '"'"'python3.11'"'"'; command -v '"'"'python3.10'"'"'; command -v '"'"'python3.9'"'"'; command -v '"'"'python3.8'"'"'; command -v '"'"'python3.7'"'"'; command -v '"'"'python3.6'"'"'; command -v '"'"'/usr/bin/python3'"'"'; command -v '"'"'/usr/libexec/platform-python'"'"'; command -v '"'"'python2.7'"'"'; command -v '"'"'/usr/bin/python'"'"'; command -v '"'"'python'"'"'; echo ENDFOUND && sleep 0'
<mgmtvm> EXEC /bin/sh -c '/usr/bin/python3 && sleep 0'
Using module file /usr/lib/python3.13/site-packages/ansible/modules/setup.py
<mgmtvm> PUT /home/user/repos/qubes-ansible-site/tmp/ansible-local-12467vtf84wp9/tmp72dxuhsn TO /home/user/.ansible/tmp/ansible-tmp-1745956217.800708-12470-17428818468008/AnsiballZ_setup.py
<mgmtvm> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1745956217.800708-12470-17428818468008/ /home/user/.ansible/tmp/ansible-tmp-1745956217.800708-12470-17428818468008/AnsiballZ_setup.py && sleep 0'
<mgmtvm> EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1745956217.800708-12470-17428818468008/AnsiballZ_setup.py && sleep 0'
<mgmtvm> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1745956217.800708-12470-17428818468008/ > /dev/null 2>&1 && sleep 0'
ok: [mgmtvm]

TASK [Create fedora-41-xfce-clone] *********************************************
task path: /home/user/repos/qubes-ansible-site/test.yml:6
<mgmtvm> ESTABLISH LOCAL CONNECTION FOR USER: user
<mgmtvm> EXEC /bin/sh -c 'echo ~user && sleep 0'
<mgmtvm> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /home/user/.ansible/tmp `"&& mkdir "` echo /home/user/.ansible/tmp/ansible-tmp-1745956218.7487633-12509-235219679054176 `" && echo ansible-tmp-1745956218.7487633-12509-235219679054176="` echo /home/user/.ansible/tmp/ansible-tmp-1745956218.7487633-12509-235219679054176 `" ) && sleep 0'
Using module file /usr/share/ansible/plugins/modules/qubesos.py
<mgmtvm> PUT /home/user/repos/qubes-ansible-site/tmp/ansible-local-12467vtf84wp9/tmpi1htapde TO /home/user/.ansible/tmp/ansible-tmp-1745956218.7487633-12509-235219679054176/AnsiballZ_qubesos.py
<mgmtvm> EXEC /bin/sh -c 'chmod u+x /home/user/.ansible/tmp/ansible-tmp-1745956218.7487633-12509-235219679054176/ /home/user/.ansible/tmp/ansible-tmp-1745956218.7487633-12509-235219679054176/AnsiballZ_qubesos.py && sleep 0'
<mgmtvm> EXEC /bin/sh -c '/usr/bin/python3 /home/user/.ansible/tmp/ansible-tmp-1745956218.7487633-12509-235219679054176/AnsiballZ_qubesos.py && sleep 0'
<mgmtvm> EXEC /bin/sh -c 'rm -f -r /home/user/.ansible/tmp/ansible-tmp-1745956218.7487633-12509-235219679054176/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
Traceback (most recent call last):
  File "/tmp/ansible_qubesos_payload_uhm4l6tw/ansible_qubesos_payload.zip/ansible/modules/qubesos.py", line 562, in core
    v.get_vm(guest)
    ~~~~~~~~^^^^^^^
  File "/tmp/ansible_qubesos_payload_uhm4l6tw/ansible_qubesos_payload.zip/ansible/modules/qubesos.py", line 233, in get_vm
    return self.app.domains[vmname]
           ~~~~~~~~~~~~~~~~^^^^^^^^
  File "/usr/lib/python3.13/site-packages/qubesadmin/app.py", line 109, in __getitem__
    raise KeyError(item)
KeyError: 'fedora-41-xfce-clone'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/qubesadmin/app.py", line 503, in clone_vm
    subprocess.check_output(runas + appmenus_cmd,
    ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
        stderr=subprocess.STDOUT)
        ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/subprocess.py", line 472, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
               **kwargs).stdout
               ^^^^^^^^^
  File "/usr/lib64/python3.13/subprocess.py", line 554, in run
    with Popen(*popenargs, **kwargs) as process:
         ~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.13/subprocess.py", line 1969, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'qvm-appmenus'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/ansible_qubesos_payload_uhm4l6tw/ansible_qubesos_payload.zip/ansible/modules/qubesos.py", line 695, in main
    rc, result = core(module)
                 ~~~~^^^^^^^^
  File "/tmp/ansible_qubesos_payload_uhm4l6tw/ansible_qubesos_payload.zip/ansible/modules/qubesos.py", line 565, in core
    v.create(guest, vmtype, label, template)
    ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/ansible_qubesos_payload_uhm4l6tw/ansible_qubesos_payload.zip/ansible/modules/qubesos.py", line 321, in create
    vm = self.app.clone_vm(template_vm, vmname, vmtype)
  File "/usr/lib/python3.13/site-packages/qubesadmin/app.py", line 510, in clone_vm
    raise qubesadmin.exc.QubesException(
        'Failed to clone appmenus') from e
qubesadmin.exc.QubesException: Failed to clone appmenus
fatal: [mgmtvm]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "command": null,
            "guest": "fedora-41-xfce-clone",
            "label": "red",
            "name": "fedora-41-xfce-clone",
            "properties": {},
            "state": "present",
            "tags": [],
            "template": "fedora-41-xfce",
            "vmtype": "TemplateVM"
        }
    },
    "msg": "Failed to clone appmenus"
}

PLAY RECAP *********************************************************************
mgmtvm                       : ok=1    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0 
```

### Additional information

The failure appears to be related to https://github.com/QubesOS/qubes-issues/issues/4809

**Comment by Guiiix** [comment]
With `qubesos.core.qube`, you can clone a template using the `clone_src` param. When specifying the `label` property explicitly, the module will enforce it. If no label is specified, if will take the same label as the source VM: 

```
- hosts: localhost
  gather_facts: false
  tasks:
    - name: Set fedora-42-xfce label
      qubesos.core.qube:
        name: fedora-42-xfce
        state: present
        klass: TemplateVM
        properties:
          label: blue

    - name: Create fedora-42-xfce TemplateVM (keep label)
      qubesos.core.qube:
        name: test-template-keeplabel
        state: present
        klass: TemplateVM
        clone_src: fedora-42-xfce

    - name: Create fedora-42-xfce TemplateVM (green label)
      qubesos.core.qube:
        name: test-template-nolabel
        state: present
        klass: TemplateVM
        clone_src: fedora-42-xfce
        properties:
          label: green

    - name: Create fedora-42-xfce StandaloneVM (keep label)
      qubesos.core.qube:
        name: test-standalone-keeplabel
        state: present
        klass: StandaloneVM
        clone_src: fedora-42-xfce

    - name: Create fedora-42-xfce StandaloneVM (green label)
      qubesos.core.qube:
        name: test-standalone-nolabel
        state: present
        klass: StandaloneVM
        clone_src: fedora-42-xfce
        properties:
          label: green

```

```
user@dom0:~/tests$ qvm-ls test-*
NAME                       STATE   CLASS         LABEL  TEMPLATE  NETVM
test-standalone-keeplabel  Halted  StandaloneVM  blue   -         sys-firewall
test-standalone-nolabel    Halted  StandaloneVM  green  -         sys-firewall
test-template-keeplabel    Halted  TemplateVM    blue   -         -
test-template-nolabel      Halted  TemplateVM    green  -         -
```
