### ISSUE TITLE
Qubes-Ansible - `become: true` fails on minimal qubes

### ISSUE THREAD

**Issue by bcduggan** [QubesOS/qubes-issues#9934]
### Qubes OS release

Qubes OS 4.2

### Brief summary

Tasks can't become root on qubes without the qubes-core-agent-passwordless-root package installed, like minimal qubes or standalone qubes based on minimal qubes.

### Steps to reproduce

1. Since it isn't yet possible to [create a standalone qube with the qubesos module](https://github.com/QubesOS/qubes-issues/issues/9932), create a standalone qube from a `dom0` terminal and apply the `created-by-mgmtvm` tag:
```console
dom0$ qvm-create --class StandaloneVM --label blue --template fedora-41-minimal fedora-41-minimal-standalone
fedora-41-minimal-standalone: Cloning root volume
dom0$ qvm-tags fedora-41-minimal-standalone set created-by-mgmtvm
```

2. Create and run the following playbook:

```yaml
---
- name: Start qubes
  hosts: local
  gather_facts: false
  tasks:
    - name: Start fedora-41-minimal-standalone
      qubesos:
        guest: fedora-41-minimal-standalone
        state: running

- name: Become root
  hosts: fedora-41-minimal-standalone
  connection: qubes
  gather_facts: false
  become: true
  tasks:
    - name: Run whoami
      ansible.builtin.command:
        cmd: whoami
      register: whoami_result
      changed_when: false

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ whoami_result.stdout }}"
```

### Expected behavior

The task should execute the command on the remote host as `root`:

```console
mgmtvm$ ansible-playbook become.yml

PLAY [Start qubes] ***************************************************************************************************************************************************************************

TASK [Start fedora-41-minimal-standalone] ****************************************************************************************************************************************************
changed: [mgmtvm]

PLAY [Become root] ***************************************************************************************************************************************************************************

TASK [Run whoami] ****************************************************************************************************************************************************************************
ok: [fedora-41-minimal-standalone]

TASK [Debug] *********************************************************************************************************************************************************************************
ok: [fedora-41-minimal-standalone] => {
    "msg": "root"
}

PLAY RECAP ***********************************************************************************************************************************************************************************
fedora-41-minimal-standalone : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
mgmtvm                     : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Actual behavior

The task can't `sudo`:

```console
mgmtvm$ ansible-playbook become.yml

PLAY [Start qubes] ***************************************************************************************************************************************************************************

TASK [Start fedora-41-minimal-standalone] ****************************************************************************************************************************************************
changed: [mgmtvm]

PLAY [Become root] ***************************************************************************************************************************************************************************

TASK [Run whoami] ****************************************************************************************************************************************************************************
fatal: [fedora-41-minimal-standalone]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python3"}, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

PLAY RECAP ***********************************************************************************************************************************************************************************
fedora-41-minimal-standalone : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0
mgmtvm                     : ok=1    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
```

### Additional information

This PR https://github.com/QubesOS/qubes-ansible/pull/5 attempts a naive solution.
