### ISSUE TITLE
SALT: `merge_tops` merges in `match: pcre`

### ISSUE THREAD

**Issue by zaz** [QubesOS/qubes-issues#9952]
### Steps to reproduce

1. Create Qubes `debian` and `debain-12-xfce`
2. Enable a top that targets `debian` with `state-one`
3. Enable a top that targets `debian` with `state-two`, but using `match: pcre`

### Expected behavior

`state-one` is run on debian and `state-two` is run on both debian and deabian-12-xfce.

### Actual behavior

Both states are run on both debian and deabian-12-xfce.

Presumably because the resulting top file looks something like this:

```
user:
  debian:
    - match: pcre
    - state-one
    - state-two
```
